package WebTKS::Model::DB::Vicidial;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

#__PACKAGE__->config(
#    schema_class => 'Vicidial::Schema',
    
#    connect_info => {
#        dsn => 'dbi:mysql:asterisk',
#        user => 'cron',
#        password => '1234',
#		AutoCommit        => 1,
#        RaiseError        => 1,
#        mysql_enable_utf8 => 1,
#    }
#);

=head1 NAME

WebForms::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<WebForms>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Vicidial::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.61

=head1 AUTHOR

root

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
